name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: ['main']

jobs:
  build:

    strategy:
      matrix:
        node-version: [20.x, 21.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint and Test
        run: npm run ci
      - uses: codecov/codecov-action@v3
